<a href="https://colab.research.google.com/github/SurZen/Python-Gapminder-Data/blob/main/BIAT_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Bring It All Together

All thanks go to Sarah Stueve and Megh Krishnaswamy for their work on the notebook.

The goal of this notebook is to exercise the acquired Python, git and Command Line knowledge obtained at the University of Arizona's Software Carpentries Spring workshop.

We will be using Google Colab as it allows for the use of the Command Line as well as Python.

The flow of this exercise is the is the following:

1. Setup
   - Open this Notebook in Google Colab
   - Obtain the required `csv`
   - Load the required packages
2. Clean the imported `csv` and extract years
3. Plot and visualize data
   - Create a list
   - Filtering
   - Plotting
4. Visualize text data
5. Saving things in Git

---

## 1. Download, Import and Clean Data

In the next cell, use a bash one-liner (`wget <raw github url>`) to download the dataset from the github repository into Google Colab's file system, and use the correct functions to import the raw csv file and index by country.

To find the raw Github url for a file, click on the 'raw' button on the top right corner in the Github link to a file.

![](https://raw.githubusercontent.com/CosiMichele/2503-carp-biat/main/github_raw_button.png)

and get CSV file from a web url:

In [1]:
!wget https://raw.githubusercontent.com/CosiMichele/2503-carp-biat/refs/heads/main/gapminder_all.csv

--2025-03-23 22:18:14--  https://raw.githubusercontent.com/CosiMichele/2503-carp-biat/refs/heads/main/gapminder_all.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 49082 (48K) [text/plain]
Saving to: ‘gapminder_all.csv’

gapminder_all.csv   100%[===================>]  47.93K  --.-KB/s    in 0.02s

2025-03-23 22:18:15 (3.07 MB/s) - ‘gapminder_all.csv’ saved [49082/49082]

---

## 2. Import required packages and data

In [5]:
# Use this cell to load packages (pandas and matplotlib)

import pandas as pd
import matplotlib as plt

In [12]:
# Import the data and set index

raw_data = pd.read_csv('gapminder_all.csv')

### 2.1 Use the right function to drop the `continent` column.

In [31]:
raw_data = pd.read_csv('/content/gapminder_all.csv')
data = pd.read_csv('/content/gapminder_all.csv')
data = data.drop("continent",axis=1)

data

,country,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,...,pop_1962,pop_1967,pop_1972,pop_1977,pop_1982,pop_1987,pop_1992,pop_1997,pop_2002,pop_2007
0,Algeria,2449.008185,3013.976023,2550.816880,3246.991771,4182.663766,4910.416756,5745.160213,5681.358539,5023.216647,...,11000948.0,12760499.0,14760787.0,17152804.0,20033753.0,23254956.0,26298373.0,29072015.0,31287142,33333216
1,Angola,3520.610273,3827.940465,4269.276742,5522.776375,5473.288005,3008.647355,2756.953672,2430.208311,2627.845685,...,4826015.0,5247469.0,5894858.0,6162675.0,7016384.0,7874230.0,8735988.0,9875024.0,10866106,12420476
2,Benin,1062.752200,959.601080,949.499064,1035.831411,1085.796879,1029.161251,1277.897616,1225.856010,1191.207681,...,2151895.0,2427334.0,2761407.0,3168267.0,3641603.0,4243788.0,4981671.0,6066080.0,7026113,8078314
3,Botswana,851.241141,918.232535,983.653976,1214.709294,2263.611114,3214.857818,4551.142150,6205.883850,7954.111645,...,512764.0,553541.0,619351.0,781472.0,970347.0,1151184.0,1342614.0,1536536.0,1630347,1639131
4,Burkina Faso,543.255241,617.183465,722.512021,794.826560,854.735976,743.387037,807.198586,912.063142,931.752773,...,4919632.0,5127935.0,5433886.0,5889574.0,6634596.0,7586551.0,8878303.0,10352843.0,12251209,14326203
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137,Switzerland,14734.232750,17909.489730,20431.092700,22966.144320,27195.113040,26982.290520,28397.715120,30281.704590,31871.530300,...,5666000.0,6063000.0,6401400.0,6316424.0,6468126.0,6649942.0,6995447.0,7193761.0,7361757,7554661
138,Turkey,1969.100980,2218.754257,2322.869908,2826.356387,3450.696380,4269.122326,4241.356344,5089.043686,5678.348271,...,29788695.0,33411317.0,37492953.0,42404033.0,47328791.0,52881328.0,58179144.0,63047647.0,67308928,71158647
139,United Kingdom,9979.508487,11283.177950,12477.177070,14142.850890,15895.116410,17428.748460,18232.424520,21664.787670,22705.092540,...,53292000.0,54959000.0,56079000.0,56179000.0,56339704.0,56981620.0,57866349.0,58808266.0,59912431,60776238
140,Australia,10039.595640,10949.649590,12217.226860,14526.124650,16788.629480,18334.197510,19477.009280,21888.889030,23424.766830,...,10794968.0,11872264.0,13177000.0,14074100.0,15184200.0,16257249.0,17481977.0,18565243.0,19546792,20434176
141,New Zealand,10556.575660,12247.395320,13175.678000,14463.918930,16046.037280,16233.717700,17632.410400,19007.191290,18363.324940,...,2488550.0,2728150.0,2929100.0,3164900.0,3210650.0,3317166.0,3437674.0,3676187.0,3908037,4115771

### 2.2 Filter the columns

When filtering columns, you can use `data.drop(columns=data.filter(like="<column to drop>").columns)`. Here, `like` is used to search for a string in the column name, and `filter` removes all matches.

In the next 2 cells, first filter the `lifeExp_` column and the the `pop_` column.

In [48]:
data = data.drop(columns=data.filter(like='pop_').columns)
data = data.drop(columns=data.filter(like='lifeExp_').columns)
data = pd.read_csv("gapminder_all.csv").set_index("country")

In [49]:
data

,continent,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,...,pop_1962,pop_1967,pop_1972,pop_1977,pop_1982,pop_1987,pop_1992,pop_1997,pop_2002,pop_2007
country,,,,,,,,,,,,,,,,,,,,,
Algeria,Africa,2449.008185,3013.976023,2550.816880,3246.991771,4182.663766,4910.416756,5745.160213,5681.358539,5023.216647,...,11000948.0,12760499.0,14760787.0,17152804.0,20033753.0,23254956.0,26298373.0,29072015.0,31287142,33333216
Angola,Africa,3520.610273,3827.940465,4269.276742,5522.776375,5473.288005,3008.647355,2756.953672,2430.208311,2627.845685,...,4826015.0,5247469.0,5894858.0,6162675.0,7016384.0,7874230.0,8735988.0,9875024.0,10866106,12420476
Benin,Africa,1062.752200,959.601080,949.499064,1035.831411,1085.796879,1029.161251,1277.897616,1225.856010,1191.207681,...,2151895.0,2427334.0,2761407.0,3168267.0,3641603.0,4243788.0,4981671.0,6066080.0,7026113,8078314
Botswana,Africa,851.241141,918.232535,983.653976,1214.709294,2263.611114,3214.857818,4551.142150,6205.883850,7954.111645,...,512764.0,553541.0,619351.0,781472.0,970347.0,1151184.0,1342614.0,1536536.0,1630347,1639131
Burkina Faso,Africa,543.255241,617.183465,722.512021,794.826560,854.735976,743.387037,807.198586,912.063142,931.752773,...,4919632.0,5127935.0,5433886.0,5889574.0,6634596.0,7586551.0,8878303.0,10352843.0,12251209,14326203
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Switzerland,Europe,14734.232750,17909.489730,20431.092700,22966.144320,27195.113040,26982.290520,28397.715120,30281.704590,31871.530300,...,5666000.0,6063000.0,6401400.0,6316424.0,6468126.0,6649942.0,6995447.0,7193761.0,7361757,7554661
Turkey,Europe,1969.100980,2218.754257,2322.869908,2826.356387,3450.696380,4269.122326,4241.356344,5089.043686,5678.348271,...,29788695.0,33411317.0,37492953.0,42404033.0,47328791.0,52881328.0,58179144.0,63047647.0,67308928,71158647
United Kingdom,Europe,9979.508487,11283.177950,12477.177070,14142.850890,15895.116410,17428.748460,18232.424520,21664.787670,22705.092540,...,53292000.0,54959000.0,56079000.0,56179000.0,56339704.0,56981620.0,57866349.0,58808266.0,59912431,60776238
Australia,Oceania,10039.595640,10949.649590,12217.226860,14526.124650,16788.629480,18334.197510,19477.009280,21888.889030,23424.766830,...,10794968.0,11872264.0,13177000.0,14074100.0,15184200.0,16257249.0,17481977.0,18565243.0,19546792,20434176
New Zealand,Oceania,10556.575660,12247.395320,13175.678000,14463.918930,16046.037280,16233.717700,17632.410400,19007.191290,18363.324940,...,2488550.0,2728150.0,2929100.0,3164900.0,3210650.0,3317166.0,3437674.0,3676187.0,3908037,4115771

### 2.3 Print index

In order to continue, you will need to use the correct format for each country's name (as they appear in data frame). In the next cell, use a `for` loop to print the index (that in this case, is the countries).

In [50]:
for i in data.index:

        print(i)

Algeria
Angola
Benin
Botswana
Burkina Faso
Burundi
Cameroon
Central African Republic
Chad
Comoros
Congo Dem. Rep.
Congo Rep.
Cote d'Ivoire
Djibouti
Egypt
Equatorial Guinea
Eritrea
Ethiopia
Gabon
Gambia
Ghana
Guinea
Guinea-Bissau
Kenya
Lesotho
Liberia
Libya
Madagascar
Malawi
Mali
Mauritania
Mauritius
Morocco
Mozambique
Namibia
Niger
Nigeria
Reunion
Rwanda
Sao Tome and Principe
Senegal
Sierra Leone
Somalia
South Africa
Sudan
Swaziland
Tanzania
Togo
Tunisia
Uganda
Zambia
Zimbabwe
Argentina
Bolivia
Brazil
Canada
Chile
Colombia
Costa Rica
Cuba
Dominican Republic
Ecuador
El Salvador
Guatemala
Haiti
Honduras
Jamaica
Mexico
Nicaragua
Panama
Paraguay
Peru
Puerto Rico
Trinidad and Tobago
United States
Uruguay
Venezuela
Afghanistan
Bahrain
Bangladesh
Cambodia
China
Hong Kong China
India
Indonesia
Iran
Iraq
Israel
Japan
Jordan
Korea Dem. Rep.
Korea Rep.
Kuwait
Lebanon
Malaysia
Mongolia
Myanmar
Nepal
Oman
Pakistan
Philippines
Saudi Arabia
Singapore
Sri Lanka
Syria
Taiwan
Thailand
Vietnam
West Bank and Gaza
Yemen Rep.
Albania
Austria
Belgium
Bosnia and Herzegovina
Bulgaria
Croatia
Czech Republic
Denmark
Finland
France
Germany
Greece
Hungary
Iceland
Ireland
Italy
Montenegro
Netherlands
Norway
Poland
Portugal
Romania
Serbia
Slovak Republic
Slovenia
Spain
Sweden
Switzerland
Turkey
United Kingdom
Australia
New Zealand

### 2.4 Extract years

Extract year from last 4 characters of each column name.

The current column names are structured as `gdpPercap_(year)`, so we want to keep the `(year)` part only for clarity when plotting GDP vs. years.

To do this we use `replace()`, which removes from the string the characters stated in the argument. This method works on strings, so we use `replace()` from Pandas Series.str vectorized string functions.

In [5]:
import pandas as pd
import matplotlib as plt

# Assuming your CSV file is named 'gapminder_all.csv'
data = pd.read_csv('gapminder_all.csv')

years = data.columns.str.replace('gdpPercap_', '')

# Convert year values to integers, saving results back to dataframe
data.columns = years.astype(int)

FileNotFoundError: [Errno 2] No such file or directory: 'gapminder_all.csv'

---

## 3 Visualizing Numerical Data: Listing and Plotting

In the next cell, select a country to plot.

In [ ]:

data.<insert code>

### 3.1 Create a list

Compare 5 countries of your choice. Create a list of countries that you are interested in.

In [ ]:
sel_countries = [<insert countries>]

### 3.2 Use index.isin() to filter

`.isin(sel_countries)` checks whether each value in the index is present in the list `sel_countries`. Make sure to save to a different dataframe.

In [ ]:
data_countries = data[<insert code>]

Plot the data. Use "GDP per capita" as x-axis label, "years" as y-axis label, and save the image with dpi=300.

In [ ]:
data_countries.T.plot()
plt.ylabel('GDP per capita')
plt.xlabel('years')
plt.savefig("countries_comparison.png", dpi=300)

---
## 4 Visualizing Text Data: Plotting and Representing Frequency Distributions

For data distributed continuously, plots are straighforward to generate. But what about **strings**?

Let's say you want to find out how many countries there are in each continent. For this, we need to access the `continent` column in each row, and count how many rows each continent bin contains. This allows us numerical data from strings, that can then be plotted.

### 4.1 Using the right data

In [ ]:
print(raw_data.head(), "\n")

In [ ]:
print(data.head())

Can we use the filtered dataframe we created in Step 2? Why/Why not?

### 4.2 What are the continent names in this dataframe?

Multiple countries can belong to the same continent. And so, the values in the column `continent` is repeated.

If we want to find out which continents are listed in the dataframe, we only need to list each possible value in the column `continent` once, i.e., unique values in the column.

We use the function `<dataframe>['col_name'].unique()` for this:

In [ ]:
# Print unique values in the column
continents = raw_data[<insert col name>].unique()
print(continents)

How many continents are present in this dataframe? Are any continents missing?

### 4.2 Filtering rows by continent:

Create a list of continents you want to plot:

In [ ]:
# Filter the DataFrame to keep only specified continents
allowed_continents = [<insert continents>]

Filter data using `.isin()`.

In [ ]:
filtered_data = raw_data[<insert code>]

### 4.3 Counting Countries in each continent

Next, we want to use the column `continent`, and count how many rows a given continent name is observed in. This gives us a frequency distribition!

For this, we use the `.value_counts())` function:

In [ ]:
# Print frequency table for each continent in the filtered dataframe
filtered_continent_freq_distr = filtered_data[<insert column>].value_counts()
<insert code>

In [ ]:
# Print frequency table for each continent in the raw dataframe
raw_continent_freq_distr = raw_data[<insert columns>].value_counts()
<insert code>

This allows us to also check if our  filter worked correctly.

### 4.4 Visualising word frequencies with Bar Plots

We will now use the frequency distributions saved in the variables `filtered_continent_freq_distr` and `raw_continent_freq_distr` to count represent how many countries each continent has.

Plot the data. Use "Continent" as x-axis label, "Frequency" as y-axis label, and save the image with dpi=300. Add a title if you want!

In [ ]:
# Generate bar plot for continent frequency in filtered dataframe:
filtered_continent_freq_distr.plot(kind='bar')
plt.xlabel(<insert desrcription>)
plt.ylabel(<insert desrcription>)
plt.title(<insert desrcription>)
plt.savefig(<insert desrcription>, dpi=300)

In [ ]:
# use the code above to generate a bar plot for all continents:
# Generate bar plot for continent frequency in filtered dataframe:
raw_continent_freq_distr.plot(kind='bar')
plt.xlabel(<insert desrcription>)
plt.ylabel(<insert desrcription>)
plt.title(<insert desrcription>)
plt.savefig(<insert desrcription>, dpi=300)

### 4.5 Visualising word frequencies with Wordclouds

Wordclouds are a fun tool to visualise how frequently a set of strings appear in a dataset. More frequent strings will be larger in size.

For this we will import the `wordcloud` python library, and the frequency distributions we printed in 4.3:

In [ ]:
from wordcloud import WordCloud

In [ ]:
filtered_wordcloud = WordCloud(width=500, height=500,
                      background_color='white').generate_from_frequencies(
                       filtered_continent_freq_distr)

In [ ]:
# Display the word cloud
plt.figure(figsize=(10, 5))
plt.imshow(filtered_wordcloud)
plt.axis('off')
plt.savefig("continents_comparison_wordcloud.png", dpi=300)

### Which continent has the most countries?

---

## 5. Save your change to Github

To save your changes to Github, you do not require to use the command line. Instead, use the button on top of the page to save to a repository of your choice.

![](https://raw.githubusercontent.com/CosiMichele/2503-carp-biat/refs/heads/main/save-in-git.png)

![](https://raw.githubusercontent.com/CosiMichele/2503-carp-biat/refs/heads/main/save-in-git2.png)

---

## 6. In your computer, pull or clone the repository using git commands and open and potentially saved image.

...aaaaand you're done!

Thank you for taking part to this workshop! It's been a pleasure having you <3